CREATE TABLE ${schema}.TB_USUARIO
(
    ID      UUID PRIMARY KEY,
    USUARIO VARCHAR(50)  NOT NULL,
    SENHA   VARCHAR(100) NOT NULL
);

CREATE TABLE ${schema}.TB_PESSOA
(
    ID              UUID PRIMARY KEY,
    NOME            VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE         NOT NULL,
    DOCUMENTO       VARCHAR(11)  NOT NULL,
    TELEFONE        VARCHAR(12)  NOT NULL,
    EMAIL           VARCHAR(50)  NOT NULL,
    TIPO            VARCHAR(20)  NOT NULL,
    ID_USUARIO      UUID,
    FOREIGN KEY (ID_USUARIO) REFERENCES ${schema}.TB_USUARIO
);

CREATE TABLE ${schema}.TB_MODALIDADE
(
    ID        UUID PRIMARY KEY,
    NOME      VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(100)
);

CREATE TABLE ${schema}.TB_PESSOA_MODALIDADE
(
    ID_PESSOA     UUID NOT NULL,
    ID_MODALIDADE UUID NOT NULL
);

CREATE TABLE ${schema}.TB_FREQUENCIA
(
    ID            UUID PRIMARY KEY,
    DATA_PRESENCA DATE NOT NULL,
    ID_PESSOA     UUID NOT NULL,
    FOREIGN KEY (ID_PESSOA) REFERENCES ${schema}.TB_PESSOA
);
